WITH AbandonedTraining AS (
SELECT
a.ACTIVITY_LEARNING_ITEM_ID AS ACTIVITY_ID,
a.ACTIVITY_TITLE,
a.ACTIVITY_TYPE,
a.ACTIVITY_EXPECTED_EFFORT AS EXPECTED_HOURS,
a.ACTIVITY_EXPECTED_EFFORT_UNITS AS EFFORT_UNITS,
a.ACTIVITY_DELIVERY_METHOD AS DELIVERY_TYPE,
l.LEARNER_ID,
l.USER_NAME AS LEARNER_NAME,
l.ASSIGNMENT_STATUS,
l.PERCENT_COMPLETE
FROM
WLF_LI_ACTIVITY_DETAILS_V a
JOIN
WLF_LI_ASSIGNMENTS_V l
ON a.ACTIVITY_LEARNING_ITEM_ID = l.ACTIVITY_ID
WHERE
l.ASSIGNMENT_STATUS IN (‘Not Started’, ‘In Progress’)
),
Top5Abandoned AS (
SELECT *
FROM (
SELECT
at.*,
COUNT(at.LEARNER_ID) OVER (PARTITION BY at.ACTIVITY_ID) AS ABANDONED_COUNT
FROM AbandonedTraining at
ORDER BY ABANDONED_COUNT DESC
)
WHERE ROWNUM <= 5
),
TrainingLast12Months AS (
SELECT
ACTIVITY_LEARNING_ITEM_ID AS ACTIVITY_ID,
ACTIVITY_TITLE,
ACTIVITY_TYPE,
ACTIVITY_EXPECTED_EFFORT AS EXPECTED_HOURS,
ACTIVITY_EXPECTED_EFFORT_UNITS AS EFFORT_UNITS,
ACTIVITY_DELIVERY_METHOD AS DELIVERY_TYPE,
CREATED_DATE
FROM
WLF_LI_ACTIVITY_DETAILS_V
WHERE
CREATED_DATE >= ADD_MONTHS(SYSDATE, -12)
)
SELECT
‘Abandoned Training Top 5’ AS REPORT_SECTION,
t5.ACTIVITY_ID,
t5.ACTIVITY_TITLE,
t5.ACTIVITY_TYPE,
t5.EXPECTED_HOURS,
t5.EFFORT_UNITS,
t5.DELIVERY_TYPE,
t5.LEARNER_ID,
t5.LEARNER_NAME,
t5.ASSIGNMENT_STATUS,
t5.PERCENT_COMPLETE,
t5.ABANDONED_COUNT,
NULL AS CREATED_DATE
FROM
Top5Abandoned t5
UNION ALL
SELECT
‘Training Created Last 12 Months’ AS REPORT_SECTION,
t.ACTIVITY_ID,
t.ACTIVITY_TITLE,
t.ACTIVITY_TYPE,
t.EXPECTED_HOURS,
t.EFFORT_UNITS,
t.DELIVERY_TYPE,
NULL AS LEARNER_ID,
NULL AS LEARNER_NAME,
NULL AS ASSIGNMENT_STATUS,
NULL AS PERCENT_COMPLETE,
NULL AS ABANDONED_COUNT,
t.CREATED_DATE
FROM
TrainingLast12Months t
ORDER BY
REPORT_SECTION,
CREATED_DATE DESC NULLS LAST,
ABANDONED_COUNT DESC NULLS LAST;
