SELECT
ACTIVITY_LEARNING_ITEM_ID AS ACTIVITY_ID,
ACTIVITY_TITLE,
ACTIVITY_TYPE,
ACTIVITY_EXPECTED_EFFORT AS EXPECTED_EFFORT_HOURS,
ACTIVITY_EXPECTED_EFFORT_UNITS AS EFFORT_UNITS,
VIRTUAL_CLASSROOM_JOIN_LINK AS VC_LINK
FROM
WLF_LI_ACTIVITY_DETAILS_V
WHERE
ACTIVITY_TYPE IN (‘ORA_DEF_ILTACTIVITY’, ‘ORA_DEF_VILT’) ; — ILT or Virtual ILT

