SELECT *
FROM (
SELECT
a.ACTIVITY_TITLE,
a.ACTIVITY_TYPE,
COUNT(l.LEARNER_ID) AS ABANDONED_COUNT
FROM
WLF_LI_ACTIVITY_DETAILS_V a
JOIN
WLF_LI_ASSIGNMENTS_V l
ON a.ACTIVITY_LEARNING_ITEM_ID = l.ACTIVITY_ID
WHERE
l.ASSIGNMENT_STATUS IN (‘Not Started’, ‘In Progress’)
GROUP BY
a.ACTIVITY_TITLE, a.ACTIVITY_TYPE
ORDER BY
ABANDONED_COUNT DESC
)
WHERE ROWNUM <= 5;
