SELECT
ACTIVITY_TITLE,
ACTIVITY_TYPE,
ACTIVITY_EXPECTED_EFFORT AS EXPECTED_HOURS,
ACTIVITY_EXPECTED_EFFORT_UNITS AS EFFORT_UNITS,
ACTIVITY_DELIVERY_METHOD AS DELIVERY_TYPE,
CREATED_DATE
FROM
WLF_LI_ACTIVITY_DETAILS_V
WHERE
CREATED_DATE >= ADD_MONTHS(SYSDATE, -12)
ORDER BY
CREATED_DATE DESC;
